[package]
name = "memento"
version = "0.1.0"
edition = "2021"
authors = [
    "Matheus Bortoleto"
]
repository = "https://github.com/explodingnuggets/memento"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
